services:
  foundation-response-api:
    container_name: foundation_response_api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8100:8100"
    networks:
      - webpage_network
    restart: on-failure

networks:
  webpage_network:
    external: True